events {
    worker_connections 1024;
}

http {
    upstream users_service_cluster {
        server users-service-1:3001;
        server users-service-2:3001;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://users_service_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Timeouts
            proxy_connect_timeout 5s;
            proxy_send_timeout 10s;
            proxy_read_timeout 10s;
        }
    }
}

